-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, email, join_date, is_admin, is_super_admin, image_url)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'erichard413@yahoo.com',
        CURRENT_TIMESTAMP,
        FALSE,
        FALSE,
        null),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'erichard413@outlook.com',
        CURRENT_TIMESTAMP,
        TRUE,
        FALSE,
        null),
       ('testsuperadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'erichard413@gmail.com',
        CURRENT_TIMESTAMP,
        TRUE,
        TRUE,
        null),
